# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f83300fa3a10685bfebb77816a20ea0b3d077209edaa2fa6674364acecbca2d1b52a377a21afd3d9c5bb0ee89d710fa62ac86bc2ba00788bc8fdaa1c55d03b0

test:
  secret_key_base: fd585496ee4786f7b83802b6c08cfe024e8878d20415a826711fd37b301f1e4cb347631cab88be9dfda95bbe29a40519153b8bf9f1fdb6acb55a1527d7fc1254

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
